output.bookingexpress= {
    service: "Express",
    vehicle: "TUKTUK",
    saverecipient: "AATest Eden Garden, Boeung Kak Road, Boeung Kak Community, Khan Daun Penh, Phnom Penh, 120306, Cambodia",
    parceltype: "Parcel type *",
    choosetype: "Large Parcel (Non-fragile Items)",
    recipient_pay: "Recipient Pay",
    confirmBtn: "Confirm",
    deliverTo: "Eden Garden, Boeung Kak Road, Boeung Kak Community, Khan Daun Penh, Phnom Penh, 120306, Cambodia",
    inputcashcollectionfield: "Enter Collection Amount ($)",
    cashcollection: "25",
    proceedtopaybtn: "Proceed to Pay",
    nextBtn: "Next",
    cashondelivery: "Cash on Delivery",
    wallet: "Wallet Balance $67.29",
    requestorderBtn: "Request Order",
    proceedtopaybtn2: "Proceed to Pay $ 0.78",
    viewtrackingBtn: "View Tracking",
    // orderHistory: "1 Eden Garden, Boeung Kak Road, Boeung Kak Community, Khan Daun Penh, Phnom Penh, 120306, Cambodia AATest • 011 111 111 25 Apr 2024 $0.78",
}