output.createItem = {
    menuTap: "Menu",
    addBtn: "",
    chooseCategory: "Select menu item category",
    selectCategory: "crab",
    namefield: "Enter menu item name",
    name: "new arrival crab",
    priceTab: "Price",
    priceNamefield: "Size (small, big,...)",
    priceName: "Big",
    priceUSDfield: "Enter price (USD)",
    price: "10",
    addmorePrice: "",
    priceName1: "small",
    price1: "7",
    optionTab: "Option",
    addOption: "",
    addOption1: "",
    optionNamefield: "Add add-on name",
    optionName: "Khmer crab",
    optionName1: "Asia crab",
    addfield: "",
    addfieldNamefield: "Enter option name",
    addfieldName: "special crab",
    addfieldName1: "expensive crab",
    addfieldNamepricefield: "Enter price (USD)",
    addfieldNameprice: "10",
    addfieldNameprice1: "20",
    addgalleryBtn: "",
    gallery: "Gallery",
    saveBtn: "Save",
    okBtn: "OK"
}
output.addnewcategory = {
    addcategoryBtn: "",
    nameCategoryfield: "Enter menu category name",
    nameCategory: "New category",
}
output.disableoptionItem = {
    editBtn: "",
    deleteBtn: "",
    updateBtn: "Update",
}
output.editStock = {
    enableStockBtn: "",
    qtyField: "",
    qty: "",
    minstockalertField: "",
    minstockalert: "",
    recommendBtn: "",
    activeBtn: "",
}